[package]
name = "bevy_agents_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
rand = "0.9.0"


# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
